/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdentifierRouteImport } from './routes/project.$identifier'
import { Route as PackageIdentifierRouteImport } from './routes/package.$identifier'
import { Route as PackageIdentifierChatRouteImport } from './routes/package.$identifier.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdentifierRoute = ProjectIdentifierRouteImport.update({
  id: '/project/$identifier',
  path: '/project/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdentifierRoute = PackageIdentifierRouteImport.update({
  id: '/package/$identifier',
  path: '/package/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdentifierChatRoute = PackageIdentifierChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PackageIdentifierRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/packages': typeof PackagesRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/package/$identifier': typeof PackageIdentifierRouteWithChildren
  '/project/$identifier': typeof ProjectIdentifierRoute
  '/package/$identifier/chat': typeof PackageIdentifierChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/packages': typeof PackagesRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/package/$identifier': typeof PackageIdentifierRouteWithChildren
  '/project/$identifier': typeof ProjectIdentifierRoute
  '/package/$identifier/chat': typeof PackageIdentifierChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/packages': typeof PackagesRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/package/$identifier': typeof PackageIdentifierRouteWithChildren
  '/project/$identifier': typeof ProjectIdentifierRoute
  '/package/$identifier/chat': typeof PackageIdentifierChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/models'
    | '/packages'
    | '/projects'
    | '/settings'
    | '/package/$identifier'
    | '/project/$identifier'
    | '/package/$identifier/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/packages'
    | '/projects'
    | '/settings'
    | '/package/$identifier'
    | '/project/$identifier'
    | '/package/$identifier/chat'
  id:
    | '__root__'
    | '/'
    | '/models'
    | '/packages'
    | '/projects'
    | '/settings'
    | '/package/$identifier'
    | '/project/$identifier'
    | '/package/$identifier/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsRoute: typeof ModelsRoute
  PackagesRoute: typeof PackagesRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  PackageIdentifierRoute: typeof PackageIdentifierRouteWithChildren
  ProjectIdentifierRoute: typeof ProjectIdentifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$identifier': {
      id: '/project/$identifier'
      path: '/project/$identifier'
      fullPath: '/project/$identifier'
      preLoaderRoute: typeof ProjectIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$identifier': {
      id: '/package/$identifier'
      path: '/package/$identifier'
      fullPath: '/package/$identifier'
      preLoaderRoute: typeof PackageIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$identifier/chat': {
      id: '/package/$identifier/chat'
      path: '/chat'
      fullPath: '/package/$identifier/chat'
      preLoaderRoute: typeof PackageIdentifierChatRouteImport
      parentRoute: typeof PackageIdentifierRoute
    }
  }
}

interface PackageIdentifierRouteChildren {
  PackageIdentifierChatRoute: typeof PackageIdentifierChatRoute
}

const PackageIdentifierRouteChildren: PackageIdentifierRouteChildren = {
  PackageIdentifierChatRoute: PackageIdentifierChatRoute,
}

const PackageIdentifierRouteWithChildren =
  PackageIdentifierRoute._addFileChildren(PackageIdentifierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsRoute: ModelsRoute,
  PackagesRoute: PackagesRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  PackageIdentifierRoute: PackageIdentifierRouteWithChildren,
  ProjectIdentifierRoute: ProjectIdentifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
